In [1]:
# Import required modules (now from root directory)
import tools.vectorstore as vs
from tools.registry import create_registry

In [2]:
# Check registry status first
registry = create_registry()
stats = registry.get_stats()
print(f"Registry Status:")
print(f"  Total files: {stats['total_files']}")
print(f"  Total chunks: {stats['total_chunks']}")
print(f"  Last updated: {stats['last_updated']}")
print(f"  Files: {stats['files']}")
print()

Registry Status:
  Total files: 3
  Total chunks: 121
  Last updated: 2025-09-28T09:10:25.202976
  Files: ['docs/knowledge/Supplier_PRD_Sop.txt', 'docs/knowledge/csv_descriptions/otif_pull.md', 'docs/knowledge/csv_descriptions/OnTime_Data.md']

In [3]:
# Get vectorstore and test search
vectorstore = vs.get_vectorstore()
print(f"Vectorstore type: {type(vectorstore)}")

# Test basic search
docs = vectorstore.similarity_search("Search the CSV data for PO355426 in OTIF, I want to know the PRD", k=5,
                                     filter={"knowledge_path": "csv_descriptions"}
                                     )
print(f"\nSearch for 'PO' found {len(docs)} documents:")

# Display results
for i, doc in enumerate(docs):
    print(f"\n--- Document {i+1} ---")
    print(f"Content preview: {doc.page_content}...")
    print(f"Source: {doc.metadata.get('filename', 'Unknown')}")
    print(f"Knowledge path: {doc.metadata.get('knowledge_path', '')}")
    print(f"Full metadata: {doc.metadata}")

Vectorstore type: <class 'langchain_chroma.vectorstores.Chroma'>

Search for 'PO' found 5 documents:

--- Document 1 ---
Content preview: # otif_pull.csv...
Source: otif_pull.md
Knowledge path: csv_descriptions
Full metadata: {'source': 'docs/knowledge/csv_descriptions/otif_pull.md', 'knowledge_path': 'csv_descriptions', 'folder': 'docs/knowledge', 'filename': 'otif_pull.md'}

--- Document 2 ---
Content preview: # View first few rows
df.head()
```

## 🔍 Understanding the OTIF Structure

### What is OTIF?
**On-Time In-Full (OTIF)** measures two critical supply chain metrics:
- **On-Time**: Did the order arrive by the promised date?
- **In-Full**: Was the complete quantity delivered?

### Key Identifier Fields
```
Purchase Order Level
    ├── document number (PO number)
    ├── internal id (System ID)
    └── po_razin_id (Composite PO-SKU identifier)
        └── Line Level
            ├── line id (Line item identifier)
            └── item (Product SKU/RAZIN)
                └── Fulfillment Level
                    ├── batch_id (Batch identifier)
                    └── inb# (Inbound shipment number)
```...
Source: otif_pull.md
Knowledge path: csv_descriptions
Full metadata: {'filename': 'otif_pull.md', 'folder': 'docs/knowledge', 'source': 'docs/knowledge/csv_descriptions/otif_pull.md', 'knowledge_path': 'csv_descriptions'}

--- Document 3 ---
Content preview: | PO365584BAHI-0000432 | PO365584BAHI-000043165860740 | PO365584 | 165860740 | BAHI-000043 | B075VDTJ6Z | Pan-EU | 0.0 | nan | nan | nan | Stryze | Pan-EU | 73773 DANYANG CHENXUAN GARMENTS CO.,LTD | Partially Received | 480 | 0 | 5.09605878 | https://6979138.app.netsuite.com/app/accounting/transactions/purchord.nl?id=35957888 | 15/05/24 | 03/06/24 | 31/05/24 | Confirmed | 04/06/24 | 2446.108214 | 9597.268517 | Q4_2024_April | Other | N | Yes | 16/08/24 | No | Pending SM | nan | 26/06/24 | 16/08/24 | nan | open_po | nan | 2 | nan | nan | nan | 12/07/24 | nan | nan | nan | nan | nan | nan | nan | nan | 12/07/24 | 13/09/24 | 13/09/24 | AI-PO365584 | 19/08/24 | 06/06/24 | 06/06/24 | 05/07/24 | To Be Tested | Yes | 30% PI 0d 70% CI 7d 0% BL 0d | 30 | 70 | 0 | Y | Y | N | nan | nan | nan | nan | 11/06/24 | nan | nan | 35.0 | nan | nan | 01/01/29 | nan | nan | nan | nan | nan | nan | nan | 1 | 2446.108214 | nan | nan | nan | nan | nan | nan | nan | nan | nan | CI-PO365584 | nan | 22/08/24 |...
Source: OnTime_Data.md
Knowledge path: csv_descriptions
Full metadata: {'folder': 'docs/knowledge', 'filename': 'OnTime_Data.md', 'knowledge_path': 'csv_descriptions', 'source': 'docs/knowledge/csv_descriptions/OnTime_Data.md'}

--- Document 4 ---
Content preview: ## Auto-Generated Overview
- **File**: otif_pull.csv
- **Rows**: 3144...
Source: otif_pull.md
Knowledge path: csv_descriptions
Full metadata: {'source': 'docs/knowledge/csv_descriptions/otif_pull.md', 'filename': 'otif_pull.md', 'folder': 'docs/knowledge', 'knowledge_path': 'csv_descriptions'}

--- Document 5 ---
Content preview: | po_razin_id | po_razin_line_unique_key | po_number | po_line_unique_key | razin | asin | marketplace | go_forward_flag | batch_id | shipment_number | item_receipt_number | acquisition_source | marketplace_header | vendor_name | final_status | total_quantity | is_zero_quantity_po_line | item_price_eur | scm_link_to_po | po_created_date | po_approval_date | po_negotiation_date | supplier_confirmation_status | supplier_confirmation_date | po_line_value | po_value | scm_po_scm_memo | po_batch | qi_flag | historical_anti_po | first_prd_date | prd_reconfirmation | prd_status | accepted_prd | planned_prd | final_prd_date | qi_date | po_open_closed | compliance | line_id | receive_final_prd_date | qc_schedule_date | prd_reconfirmed_date | receive_first_prd_date | ffw_booking_ts | spd_ts | batch_spd | stock_pickup_date | batch_telex_date | ffwp_telex_release_date | supplier_telex_release_date | telex_release_date | packaging_file_date | po_im_date_value | po_sm_date_value | pi_invoice_number...
Source: OnTime_Data.md
Knowledge path: csv_descriptions
Full metadata: {'folder': 'docs/knowledge', 'knowledge_path': 'csv_descriptions', 'filename': 'OnTime_Data.md', 'source': 'docs/knowledge/csv_descriptions/OnTime_Data.md'}

In [4]:
docs

[Document(id='8aab39c9-caf8-42fc-981a-c49fabded257', metadata={'source': 'docs/knowledge/csv_descriptions/otif_pull.md', 'knowledge_path': 'csv_descriptions', 'folder': 'docs/knowledge', 'filename': 'otif_pull.md'}, page_content='# otif_pull.csv'),
 Document(id='2a39172f-8e5a-4340-839f-13dbcdb16ecf', metadata={'filename': 'otif_pull.md', 'folder': 'docs/knowledge', 'source': 'docs/knowledge/csv_descriptions/otif_pull.md', 'knowledge_path': 'csv_descriptions'}, page_content='# View first few rows\ndf.head()\n```\n\n## 🔍 Understanding the OTIF Structure\n\n### What is OTIF?\n**On-Time In-Full (OTIF)** measures two critical supply chain metrics:\n- **On-Time**: Did the order arrive by the promised date?\n- **In-Full**: Was the complete quantity delivered?\n\n### Key Identifier Fields\n```\nPurchase Order Level\n    ├── document number (PO number)\n    ├── internal id (System ID)\n    └── po_razin_id (Composite PO-SKU identifier)\n        └── Line Level\n            ├── line id (Line item identifier)\n            └── item (Product SKU/RAZIN)\n                └── Fulfillment Level\n                    ├── batch_id (Batch identifier)\n                    └── inb# (Inbound shipment number)\n```'),
 Document(id='a67b2088-3991-487f-b88a-38a7621ea444', metadata={'folder': 'docs/knowledge', 'filename': 'OnTime_Data.md', 'knowledge_path': 'csv_descriptions', 'source': 'docs/knowledge/csv_descriptions/OnTime_Data.md'}, page_content='| PO365584BAHI-0000432 | PO365584BAHI-000043165860740 | PO365584 | 165860740 | BAHI-000043 | B075VDTJ6Z | Pan-EU | 0.0 | nan | nan | nan | Stryze | Pan-EU | 73773 DANYANG CHENXUAN GARMENTS CO.,LTD | Partially Received | 480 | 0 | 5.09605878 | https://6979138.app.netsuite.com/app/accounting/transactions/purchord.nl?id=35957888 | 15/05/24 | 03/06/24 | 31/05/24 | Confirmed | 04/06/24 | 2446.108214 | 9597.268517 | Q4_2024_April | Other | N | Yes | 16/08/24 | No | Pending SM | nan | 26/06/24 | 16/08/24 | nan | open_po | nan | 2 | nan | nan | nan | 12/07/24 | nan | nan | nan | nan | nan | nan | nan | nan | 12/07/24 | 13/09/24 | 13/09/24 | AI-PO365584 | 19/08/24 | 06/06/24 | 06/06/24 | 05/07/24 | To Be Tested | Yes | 30% PI 0d 70% CI 7d 0% BL 0d | 30 | 70 | 0 | Y | Y | N | nan | nan | nan | nan | 11/06/24 | nan | nan | 35.0 | nan | nan | 01/01/29 | nan | nan | nan | nan | nan | nan | nan | 1 | 2446.108214 | nan | nan | nan | nan | nan | nan | nan | nan | nan | CI-PO365584 | nan | 22/08/24 |'),
 Document(id='e884dd4d-6125-4415-b99c-f59a79e16823', metadata={'source': 'docs/knowledge/csv_descriptions/otif_pull.md', 'filename': 'otif_pull.md', 'folder': 'docs/knowledge', 'knowledge_path': 'csv_descriptions'}, page_content='## Auto-Generated Overview\n- **File**: otif_pull.csv\n- **Rows**: 3144'),
 Document(id='3b00af3a-03be-4771-bb2c-987c83c75e44', metadata={'folder': 'docs/knowledge', 'knowledge_path': 'csv_descriptions', 'filename': 'OnTime_Data.md', 'source': 'docs/knowledge/csv_descriptions/OnTime_Data.md'}, page_content='| po_razin_id | po_razin_line_unique_key | po_number | po_line_unique_key | razin | asin | marketplace | go_forward_flag | batch_id | shipment_number | item_receipt_number | acquisition_source | marketplace_header | vendor_name | final_status | total_quantity | is_zero_quantity_po_line | item_price_eur | scm_link_to_po | po_created_date | po_approval_date | po_negotiation_date | supplier_confirmation_status | supplier_confirmation_date | po_line_value | po_value | scm_po_scm_memo | po_batch | qi_flag | historical_anti_po | first_prd_date | prd_reconfirmation | prd_status | accepted_prd | planned_prd | final_prd_date | qi_date | po_open_closed | compliance | line_id | receive_final_prd_date | qc_schedule_date | prd_reconfirmed_date | receive_first_prd_date | ffw_booking_ts | spd_ts | batch_spd | stock_pickup_date | batch_telex_date | ffwp_telex_release_date | supplier_telex_release_date | telex_release_date | packaging_file_date | po_im_date_value | po_sm_date_value | pi_invoice_number')]

In [5]:
# Load the otif_pull.csv file
import pandas as pd
otif_df = pd.read_csv('docs/csvs/otif_pull.csv')
# Filter the data for the user query PO355426
result = otif_df[otif_df['document number'] == 'PO377368']

In [6]:
result

,Unnamed: 0,internal id,date created,document number,associated brands,id,name,supplier confirmation status,final status,memo (main),...,current status,sub status,days bucket,team,reporting status,reporting days bucket,l2 final status,final poc,final team,snapshot_ts
0,0,66928377,2025-08-13,PO377368,Prestee,NaN,"74964 JIANGSU PLUS INTERNATIONAL TRADING CO.,LTD",Confirmed,Pending Receipt,Razor_July_Cycle_2025,...,20. Pre Pickup Check,20a. QC Release Missing,On-Track,CN,05. Pickup + Shipping,NaN,QC scheduled,Young Cao,Compliance & QC,2025-09-23 14:45:50.495636+00:00
998,998,66928377,2025-08-13,PO377368,Prestee,NaN,"74964 JIANGSU PLUS INTERNATIONAL TRADING CO.,LTD",Confirmed,Pending Receipt,Razor_July_Cycle_2025,...,20. Pre Pickup Check,20a. QC Release Missing,On-Track,CN,05. Pickup + Shipping,NaN,QC scheduled,Young Cao,Compliance & QC,2025-09-23 14:45:50.495636+00:00
2322,2322,66928377,2025-08-13,PO377368,Prestee,NaN,"74964 JIANGSU PLUS INTERNATIONAL TRADING CO.,LTD",Confirmed,Pending Receipt,Razor_July_Cycle_2025,...,20. Pre Pickup Check,20a. QC Release Missing,On-Track,CN,05. Pickup + Shipping,NaN,QC scheduled,Young Cao,Compliance & QC,2025-09-23 14:45:50.495636+00:00

In [7]:
otif_df

,Unnamed: 0,internal id,date created,document number,associated brands,id,name,supplier confirmation status,final status,memo (main),...,current status,sub status,days bucket,team,reporting status,reporting days bucket,l2 final status,final poc,final team,snapshot_ts
0,0,66928377,2025-08-13,PO377368,Prestee,NaN,"74964 JIANGSU PLUS INTERNATIONAL TRADING CO.,LTD",Confirmed,Pending Receipt,Razor_July_Cycle_2025,...,20. Pre Pickup Check,20a. QC Release Missing,On-Track,CN,05. Pickup + Shipping,NaN,QC scheduled,Young Cao,Compliance & QC,2025-09-23 14:45:50.495636+00:00
1,1,67247335,2025-09-17,PO378507,Bolt Dropper,NaN,"73109 YOLINK FASTENER (JIAXING) CO., LTD",Rejected,Pending Receipt,Razor_August_Cycle_2025,...,02. Supplier Confirmation Pending,02c. Rejected,01-03,CN,01. Pre Production,NaN,No L2 Status,Paul Fong,CM,2025-09-23 14:45:50.495636+00:00
2,2,63648408,2025-04-14,PO372477,Kidzlane,NaN,"74634 Wah Shing Toys Co.,Ltd.",Confirmed,Partially Received,Q4_2025_Batch1,...,30. Stock Delivery Pending,30c. Appointment in Future,On-Track,CN,07. Arrived,NaN,No L2 Status,NaN,NaN,2025-09-23 14:45:50.495636+00:00
3,3,67247335,2025-09-17,PO378507,Bolt Dropper,NaN,"73109 YOLINK FASTENER (JIAXING) CO., LTD",Rejected,Pending Receipt,Razor_August_Cycle_2025,...,02. Supplier Confirmation Pending,02c. Rejected,01-03,CN,01. Pre Production,NaN,No L2 Status,Paul Fong,CM,2025-09-23 14:45:50.495636+00:00
4,4,63648408,2025-04-14,PO372477,Kidzlane,NaN,"74634 Wah Shing Toys Co.,Ltd.",Confirmed,Partially Received,Q4_2025_Batch1,...,30. Stock Delivery Pending,30c. Appointment in Future,On-Track,CN,07. Arrived,NaN,No L2 Status,NaN,NaN,2025-09-23 14:45:50.495636+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,3139,67247416,2025-09-17,PO378586,JTJ Sourcing,NaN,70370 GST ENTERPRISE LIMITED,Confirmed,Pending Receipt,Razor_August_Cycle_2025,...,06. Packaging Pending,06b. SCM Check Pending,01-03,CN,01. Pre Production,NaN,No L2 Status,Darren Fernandes,Packaging,2025-09-23 14:45:50.495636+00:00
3140,3140,67247418,2025-09-17,PO378588,Jewelkeeper,NaN,75146 TE Electronic Manufacturing Ltd.,Rejected,Pending Receipt,Razor_August_Cycle_2025,...,02. Supplier Confirmation Pending,02c. Rejected,01-03,CN,01. Pre Production,NaN,No L2 Status,Jeremy Lin,CM,2025-09-23 14:45:50.495636+00:00
3141,3141,65828912,2025-05-28,PO373879,Vdomus,NaN,71649 Shenzhen Hongdashun acrylic Products Co....,Confirmed,Pending Receipt,Consolidation_PO366387,...,A. Anti PO Line,A. Anti PO Line,On-Track,CN,00. Anti + Blocked,NaN,c. Never pickup,NaN,NaN,2025-09-23 14:45:50.495636+00:00
3142,3142,65568609,2025-05-12,PO373323,InstallGear,NaN,75242 KINGSUN NETWORK DEVICES VIETNAM COMPANY ...,Confirmed,Pending Receipt,Q4_2025_Batch2,...,28. Telex Release Pending,28a. In Transit - Supplier Pending,On-Track,CN,06. On Sea,NaN,Yellow2:Not Released_Pending Vendor release to...,Dede Wu,SM,2025-09-23 14:45:50.495636+00:00
3143,3143,65568609,2025-05-12,PO373323,InstallGear,NaN,75242 KINGSUN NETWORK DEVICES VIETNAM COMPANY ...,Confirmed,Pending Receipt,Q4_2025_Batch2,...,28. Telex Release Pending,28a. In Transit - Supplier Pending,On-Track,CN,06. On Sea,NaN,Yellow2:Not Released_Pending Vendor release to...,Dede Wu,SM,2025-09-23 14:45:50.495636+00:00

In [8]:
targeted_docs = vectorstore.similarity_search(
                    "column names reference",
                    k=10,
                    filter={
                        "$and": [
                            {"section_type": {"$eq": "column_reference"}},
                            {"filename": {"$eq": "otif_pull.md"}}
                        ]
                    }
                )

In [10]:
targeted_docs

[Document(id='7a6bcd02-e8a6-489e-bc67-fd6b3e8c240f', metadata={'folder': 'docs/knowledge', 'knowledge_path': 'csv_descriptions', 'source': 'docs/knowledge/csv_descriptions/otif_pull.md', 'filename': 'otif_pull.md', 'section_type': 'column_reference'}, page_content='## 📊 Column Names Reference\n\n**Format: column_name | description | synonymous_names**')]